### ISSUE TITLE
return promise

### ISSUE THREAD

**Issue by kylemac** [snowshoestamp/snowshoe_node#1]
I suggest returning a [promise](https://github.com/petkaantonov/bluebird) from `snowsh.post` to allow for some nice async behaviors. this wouldn't be too difficult to implement either since the lib only has two behaviors

**Comment by RasPhilCo** [comment]
Agreed! That was my initial approach but I found oauth's behavior odd. I decided a callback could win out the day for the initial release knowing a promise would come in a future release and win the war.

**Comment by RasPhilCo** [comment]
@kylemac If you get a sec, check out #6. Any feedback would be much appreciated! I will merge it into master sometime next week.
