### ISSUE TITLE
Mistake in require OAuth statement

### ISSUE THREAD

**Issue by kaleguy** [snowshoestamp/snowshoe_node#3]
In snowshoe.js

 `var OAuth = require('OAuth');`

needs to be

`var OAuth = require('oauth');`

First one seems to work on my local machine (Mac) but fails on Heroku.

**Comment by RasPhilCo** [comment]
Thanks! We'll take a look and try to reproduce.

**Comment by andrewtennison** [comment]
i can back this up, causes it to fail on both Heroku and Openshift
