### ISSUE TITLE
on error JSON.parse SyntaxError

### ISSUE THREAD

**Issue by andrewtennison** [snowshoestamp/snowshoe_node#4]
SyntaxError: Unexpected token o
    at Object.parse (native)
    at /node_modules/snowshoe/lib/snowshoe.js:23:24

The response is:
error = { statusCode: 400, data: '{"receipt": "IEgB0LjqKtLG0ncF7+8cohhUrZ4=", "created": "2016-01-21 08:20:51.545927", "secure": false, "error": {"message": "Stamp not found", "code": 32}}' }

So just error.data needs to be passed.

**Comment by RasPhilCo** [comment]
@andrewtennison Thanks for the input! I've just noticed npm is on an old version, release v0.1.0, which is probably why you are seeing this. Release v0.1.1 fixed this. Additionally, I have release v0.2.0 ready to go -- PR #6 -- if you'd like to take a look. The client can now return a promise or use a callback.
